#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Akira Matsumoto <akiram8427@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math  

ans = 0.0
count = 0.0
for line in sys.stdin:
    ans = float(line)
    count += 1

if count > 2 :
    print("error:二つ以上の文字が入力されました")
    sys.exit(1)
else :    
    n = math.cos(ans)
    print(n)
