#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Akira Matsumoto <akiram8427@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math  

ans = 0.0
for line in sys.stdin:
    ans = float(line)

n = math.cos(ans)
print(n)
