#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Akira Matsumoto <akiram8427@gmail.com>

import sys
   

def tonum(s):
    try:
        ans += int(line)
    except:
        ans += float(line)
 

ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)
