name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: ["3.7"]
    steps: 
      - uses: actions/checkout@v3
      - name: Alltest
        run: bash -xv ./test.bash
